spring:
  liquibase:
    enabled: false
    change-log: classpath:db/changelog/db.changelog-master.xml
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/render_postgres_demo}
    username: ${SPRING_DATASOURCE_USERNAME:abaulderstone}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    generate-ddl: true
